services:
  - type: web
    name: stegophy-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn stgphy_v2:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
